### PR TITLE
Expose `Compactor` and `Manifest` structs publicly for `CompactionScheduler`

### LINKED ISSUE #1099: Export what's required to implement compaction scheduler suppliers
**Describe the bug**

Despite [having a builder method](https://docs.rs/slatedb/latest/slatedb/struct.DbBuilder.html#method.with_compaction_scheduler_supplier) to supply a compaction scheduler, [there's a bunch of structs](https://github.com/slatedb/slatedb/blob/main/slatedb/src/size_tiered_compaction.rs#L6-L9) and modules that slatedb needs to export so that it's possible to implement a compaction scheduler.

### PR DESCRIPTION
**Pull request by criccomini**
## Summary

While working on #1181, I noticed many oddities in the compactor. These include:

- Exposing a `CompactorState` publicly to the user, but without any accessible functions or fields.
- Not exposing `Manifest` publicly at all, which makes pluggable compactor scheduling impossible.
- Calling things a compaction when they are a spec.
- Inconsistent data modeling between `DbState` -> `Manifest` -> `CoreDbState` and `CompactorState` -> `Compactions` -> `[missing]`
- Various `pub` fields in `pub(crate)` structs.

This PR aims to address these concerns.

Fixes #1099.

## Changes

- Rename `CoreDbState` to `ManifestCore` and add a `CompactionsCore` to unify the flatbuffer data model. The pattern is now State -> Object -> ObjectCore. So we have DbState -> Manifest -> ManifestCore and CompactorState -> Compactions -> CompactionsCore. The CompactorState also includes the manifest, so it also has Manifest -> ManifestCore.
- Use `CompactorStateView` instead of `CompactorState` in `CompactionScheduler`
- Expose the following publicly:
  - SequenceTracker
  - SortedRun
  - SsTableId
  - SsTableHandle
  - SsTableInfo
  - ManifestCore
  - Compaction

## Notes for Reviewers

This PR touches many files, but is mostly renaming and visibility changes. It's best read in commit order.

I opted to expose fields directly (e.g. `SsTableInfo::first_key`) rather than using fn's (e.g. `SsTableInfo::first_key()`) except when field transformation is needed (e.g. `CompactionsCore::recent_compactions()`, which returns an interator instead of the raw `BTreeMap`).

The files worth focusing most on are:

- compactor.rs
- compactor_state.rs
- compactor_state_protocol.rs
- db_state.rs
- size_tiered_compaction.rs

## Checklist

- [x] Small, scoped PR (< 500 total lines excluding tests); or opened as Draft with a plan on how to break it into smaller pieces
- [x] Linked related issue(s) or added context in the description
- [x] Self-reviewed the diff; added comments for tricky parts
- [x] Tests added/updated and passing locally
- [x] Ran `cargo fmt`, `cargo clippy --all-targets --all-features`, and `cargo nextest run --all-features`
- [x] Called out any breaking changes and provided migration notes
- [x] Considered performance impact; added notes or benchmarks if relevant

Thank you for the review! 🙏

### CODE REVIEW

File: slatedb/src/admin.rs [hunk 1]
```diff
@@ -773,6 +773,8 @@ mod tests {
             7
         );
         let recent = latest_compactions
+            .get("core")
```
Comment (criccomini) [inline slatedb/src/admin.rs:776]: This is a bit clunky, but is the way the Manifest JSON encoding works right now as well. We expose the full data model rather than just the core. This includes the manifest file version (and compaction file version) as well. At some point we should make the JSON encoding use a nicer data model, but for now, I'm just keeping things consistent.

**Review by agavra — APPROVED** [review]
Nice, I particularly like renaming `CoreDbState` -> `ManifestCore`, that naming always confused me when trying to find the cod object representing the manifest. This makes the 1:1 relationship clear 🙏
