### PR TITLE
fix(gc): Reimplement the garbage collector without crossbeam.

### LINKED ISSUE #380: Don't Block Tokio Runtime in GC Thread
We should be using `tokio::select!` in the GC thread since `crossbeam_channel::select!` is synchronous so this would block the tokio runtime thread.

There may be some other changes required to make sure we don't block the tokio runtime

_Originally posted by @rodesai in https://github.com/slatedb/slatedb/pull/367#discussion_r1872214282_

### PR DESCRIPTION
**Pull request by calavera**
Introduce a simplified version of the GarbageCollector that doesn't use crossbeam::channels for concurrency control.

This new implementation also removes the state machine that made the code more complex in favor of purposely defined functions. This fixes some fleaky tests that could crash because the GC thread terminated ahead of time and made the database enter an error state.

This change also asumes that the admin tools don't run in the same process than the actual database, hence there is no need of a fully dedicated system thread to run the garbage collector, it can run in a Tokio task. The caller can decide to run the task in a separated system thread if it's necessary for the task at hand.

Fixes #380 

NOTE: GitHub collapses the garbage_collector.rs file, be sure to review it because that's where the bulk of the changes are:

### CODE REVIEW

File: slatedb-cli/src/main.rs [hunk 1]
```diff
@@ -22,6 +25,19 @@ async fn main() -> Result<(), Box<dyn Error>> {
     let args: CliArgs = parse_args();
     let path = Path::from(args.path.as_str());
     let object_store = admin::load_object_store_from_env(args.env_file)?;
+
+    let cancellation_token = CancellationToken::new();
```
Comment (flaneur2020) [inline slatedb-cli/src/main.rs:29]: i think this cancellation token is worth promoting in all critical structures :+1:. `context` is something I miss a lot from Go when moving to Rust, it forces us to think clearly about how the canceling is handled in the early design and provides a standardized approach for it.

File: slatedb/src/garbage_collector/compacted_gc.rs [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+            }
+        }
+        Ok(active_ssts)
+    }
+}
+
+impl GcTask for CompactedGcTask {
+    /// Collect garbage from the compacted SSTs. This will delete any compacted SSTs that are
+    /// older than the minimum age specified in the options and are not active in the manifest.
+    async fn collect(&self, utc_now: DateTime<Utc>) -> Result<(), SlateDBError> {
```
Comment (flaneur2020) [inline slatedb/src/garbage_collector/compacted_gc.rs:62]: does this `collect()` method also have plans to have cancellation token handled? Its execution might also be relatively time consuming imo.

(just for discussion, if needed, I think it will be nice to have a separate PR for it.)

Comment (calavera) [reply slatedb/src/garbage_collector/compacted_gc.rs:62]: I didn't think about it, but it might be a good idea. I just copied the three gc tasks from the root of the module to make the code easier to understand.

Comment (flaneur2020) [reply slatedb/src/garbage_collector/compacted_gc.rs:62]: i love this separation a lot 👍, each file has a single responsibility, which makes it much easier for readers to understand what they do

File: slatedb-cli/src/main.rs (hunk 1 above)
Comment (calavera) [reply slatedb-cli/src/main.rs:29]: They are not the same as Go's context, I would not prematurely optimize the code to pass them everywhere like you'd do in Go. As far as I can tell, this is only needed to run the GC in the background at the moment, if there are more use cases in the future, we can pass it along. I put it at the top of this file, so it's easier to spot and reuse when necessary.

Comment (flaneur2020) [reply slatedb-cli/src/main.rs:29]: make sense :+1:

**Review by flaneur2020 — APPROVED** [review]
looks great to me, though it's good to have another 👀.

File: slatedb/src/db.rs [hunk 3]
```diff
@@ -358,6 +359,8 @@ pub struct Db {
     write_task: Mutex<Option<tokio::task::JoinHandle<Result<(), SlateDBError>>>>,
     compactor: Mutex<Option<Compactor>>,
     garbage_collector: Mutex<Option<GarbageCollector>>,
+
```
Comment (criccomini) [inline slatedb/src/db.rs:362]:
```suggestion
```

File: slatedb/src/garbage_collector.rs [hunk 4]
```diff
@@ -1,676 +1,294 @@
...
-    wal_options: Option<GarbageCollectorDirectoryOptions>,
-    status: DirGcStatus,
-}
-
-impl WalGcTask {
-    fn new(
+    /// Start the garbage collector in an async task.
+    ///
+    /// This method will start the garbage collector task that performs the actual garbage collection
+    /// in a Tokio asyn task.
```
Comment (criccomini) [inline slatedb/src/garbage_collector.rs:93]:
```suggestion
    /// in a Tokio async task.
```

**Review by criccomini — APPROVED** [review]
Looks good! I'm going to try and resolve the errors and merge.

@agavra This is is probably worth a (non-blocking) look on your end since IIRC, you added the state stuff to the GC.

**Comment by criccomini** [comment]
Ok, so the rebase looks a bit more complex than I had anticipated. The main issue is that #558 introduced the concept of `ObjectStores`, which get passed to `TableStore`.

I've submitted a PR to your branch to fix the issues:

https://github.com/calavera/slatedb/pull/1

Once you review and merge that in, I think we should be good to go.

**Comment by calavera** [comment]
@criccomini I've merged your changes in.

**Comment by agavra** [comment]
> @agavra This is is probably worth a (non-blocking) look on your end since IIRC, you added the state stuff to the GC.

Will take a look next week when I get back from London!
