### PR TITLE
Support Ttl::ExpireAt for fixed absolute expiration timestamps

### LINKED ISSUE #1447: Support `Ttl:ExpireAt`
## Summary

SlateDB currently supports `Ttl::ExpireAfter(duration)`, which computes `expire_ts` as `now() + duration` at write time. This means every write to the same key produces a different `expire_ts`. We'd like support for `Ttl::ExpireAt(timestamp)` that sets a fixed absolute expiration time.

## Motivation

When using merge operators with `Ttl::ExpireAfter`, each merge entry for the same key gets a unique `expire_ts`. During compaction, `MergeOperatorIterator::is_matching_entry` requires `expire_ts` to match exactly (when `merge_different_expire_ts` is `false`):

```rust
fn is_matching_entry(&self, entry: &RowEntry, key: &Bytes, first_expire_ts: Option<i64>) -> bool {
    entry.key == *key && (self.merge_different_expire_ts || first_expire_ts == entry.expire_ts)
}
```

This causes merge entries to **never be resolved during compaction**, since the compactor treats each entry as belonging to a different logical key.

## Proposal

Add `Ttl::ExpireAt(i64)` as a variant alongside the existing `Ttl::ExpireAfter(Duration)`. This allows callers to set a fixed absolute expiration timestamp, ensuring all writes to the same key share the same `expire_ts`.

For example, in a timeseries use case with hourly buckets, all writes to the same bucket could use `Ttl::ExpireAt(bucket_end + retention_period)`, and the merge operator would correctly combine them during compaction.

### PR DESCRIPTION
**Pull request by agavra**
## Summary

Add ExpireAt(i64) variant to the Ttl enum, allowing callers to set a fixed absolute expiration timestamp instead of a relative duration. Fixes #1447 

## Changes

- Adds the `Ttl:ExpireAt` variant
- Tests

## Notes for Reviewers

N/A

## Checklist

- [X] Small, scoped PR (< 500 total lines excluding tests); or opened as Draft with a plan on how to break it into smaller pieces
- [x] Linked related issue(s) or added context in the description
- [x] Self-reviewed the diff; added comments for tricky parts
- [x] Tests added/updated and passing locally
- [x] Ran `cargo fmt`, `cargo clippy --all-targets --all-features`, and `cargo nextest run --all-features`
- [x] Called out any breaking changes and provided migration notes
- [x] Considered performance impact; added notes or benchmarks if relevant

Thank you for the review! 🙏

### CODE REVIEW

**Comment by apurvam** [comment]
This seems to be a config-only change. I'm assuming he reader/compactor just calls `expire_ts_from` on `MergeOptions`, which returns the ttl based on the config? Super neat if so.

**Comment by agavra** [comment]
Essentially! Internally we already stored timestamps as `expire_at` instead of anything relative to `create_ts` so it's a really simple addition (so the path is a little different from what you describe, but the result is more or less the same).

File: bindings/uniffi/src/config.rs [hunk 1]
```diff
@@ -103,6 +103,8 @@ pub enum Ttl {
     NoExpiry,
     /// Expire the value after the given number of clock ticks.
     ExpireAfterTicks(u64),
+    /// Expire the value at the given absolute timestamp (clock ticks).
+    ExpireAtTimestamp(i64),
```
Comment (agavra) [inline bindings/uniffi/src/config.rs]: nit: updating this to `ExpireAt` to match

**Review by criccomini — APPROVED** [review]
Can you update https://github.com/slatedb/slatedb/blob/main/website/src/content/docs/docs/design/time.mdx to mention the new type?
