### PR TITLE
Shutdown cleanly in `test_concurrent_writers_and_readers`

### LINKED ISSUE #806: `test_concurrent_writers_and_readers` is failing silently
**Describe the bug**
I see this occasionally when I run `test_concurrent_writers_and_readers` in a loop:

```
2025-08-19T17:49:34.377383Z  INFO slatedb::clock: Clock tick 1755625774376 is lagging behind the last known tick 1755625774377. Sleeping 2ms to potentially resolve skew before returning InvalidClockTick.    
2025-08-19T17:49:34.378618Z  WARN slatedb::db::builder: compactor thread exited [error=background task shutdown]    
2025-08-19T17:49:34.378673Z  INFO slatedb::db: compactor task exited [result=Ok(())]    

thread 'tokio-runtime-worker' panicked at slatedb/tests/db.rs:107:26:
Failed to read value: Error { msg: "background task shutdown", kind: System, source: None }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2025-08-19T17:49:34.378749Z  INFO slatedb::batch_write: write task shutdown complete    
2025-08-19T17:49:34.378802Z  INFO slatedb::db: write task exited [result=Ok(())]    
2025-08-19T17:49:34.379056Z  INFO slatedb::mem_table_flush: memtable flush thread exiting [result=Err(BackgroundTaskShutdown)]    
2025-08-19T17:49:34.379086Z  WARN slatedb::mem_table_flush: memtable flush task exited with error [error=background task shutdown]    
2025-08-19T17:49:34.379098Z  INFO slatedb::mem_table_flush: notifying in-memory memtable of error    
2025-08-19T17:49:34.379131Z  INFO slatedb::db: mem table flush task exited [result=Err(BackgroundTaskShutdown)]    
test test_concurrent_writers_and_readers ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.23s

     Running unittests src/main.rs (target/debug/deps/bencher-33d8c50ae4dfd038)
```

**To Reproduce**

Run `test_concurrent_writers_and_readers` with info logging and wait until it sits for a while.

**Expected behavior**
I expected the test to fail when the compactor dies.
I also expect the test to pass.

### PR DESCRIPTION
**Pull request by criccomini**
It looks like we were not doing a clean shutdown in `test_concurrent_writers_and_readers`. Instead, we were calling `abort()` on the reader threads and then ignoring errors returned by the reader tasks.

This PR updates the code to use a cancellation token to shutdown cleanly and then verify the readers have no errors.

Fixes #806

### CODE REVIEW

**Comment by criccomini** [comment]
@KarinaMilet this fixes the timeouts you were seeing in #788

File: slatedb/tests/db.rs [hunk 1]
```diff
@@ -10,9 +10,19 @@ use std::collections::HashMap;
 use std::sync::atomic::{AtomicU64, Ordering};
 use std::sync::Arc;
 use std::time::Duration;
+use tokio_util::sync::CancellationToken;
+use tracing_subscriber::fmt::format::FmtSpan;
+use tracing_subscriber::EnvFilter;
 
 #[tokio::test(flavor = "multi_thread", worker_threads = 8)]
 async fn test_concurrent_writers_and_readers() {
+    let filter = EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("debug"));
```
Comment (calavera) [inline slatedb/tests/db.rs:19]: Is this necessary or it’s here for debugging purposes?

Comment (criccomini) [reply slatedb/tests/db.rs:19]: Ah, I added it so logs are visible with --nocapture. We have a harness that does this for all unit tests, but we have to do it manually here since it's an integration test.

**Review by calavera — APPROVED** [review]
I'm glad you figured this out. 🥳

**Comment by criccomini** [comment]
LMK if anyone has any concerns. Merged.
