### PR TITLE
Fix flaky db reader reestablish test

### LINKED ISSUE #1439: Flaky Test `db_reader_get_returns_correct_merge_result_after_reestablish_from_l0`
https://github.com/slatedb/slatedb/actions/runs/23556137448/job/68583324104?pr=1434

```
        FAIL [  30.056s] slatedb db_reader::tests::db_reader_get_returns_correct_merge_result_after_reestablish_from_l0
  stdout ───

    running 1 test
    2026-03-25T18:01:25.252275Z  INFO slatedb::db::builder: opening SlateDB database [path=tmp/test_db_reader_merge_reestablish_from_l0, settings={"flush_interval":null,"wal_enabled":true,"manifest_poll_interval":"1s","manifest_update_timeout":"300s","min_filter_keys":1000,"filter_bits_per_key":10,"l0_sst_size_bytes":67108864,"l0_max_ssts":8,"max_unflushed_bytes":1073741824,"compactor_options":null,"compression_codec":null,"object_store_cache_options":{"root_folder":null,"max_cache_size_bytes":17179869184,"part_size_bytes":4194304,"cache_puts":false,"preload_disk_cache_on_startup":null,"scan_interval":"3600s"},"garbage_collector_options":null,"default_ttl":null}]
    2026-03-25T18:01:25.256731Z DEBUG slatedb::retrying_object_store: not retrying object store operation [error=AlreadyExists { path: "tmp/test_db_reader_merge_reestablish_from_l0/manifest/00000000000000000003.manifest", source: AlreadyExists { path: "tmp/test_db_reader_merge_reestablish_from_l0/manifest/00000000000000000003.manifest" } }]
    2026-03-25T18:01:25.256807Z DEBUG slatedb::mem_table_flush: conflicting manifest version. updating and retrying write again.
    test db_reader::tests::db_reader_get_returns_correct_merge_result_after_reestablish_from_l0 ... FAILED

    failures:

    failures:
        db_reader::tests::db_reader_get_returns_correct_merge_result_after_reestablish_from_l0

    test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 1278 filtered out; finished in 30.01s

  stderr ───

    thread 'db_reader::tests::db_reader_get_returns_correct_merge_result_after_reestablish_from_l0' (18096) panicked at slatedb/src/db_reader.rs:2397:13:
    timed out waiting for reader to reestablish from the new manifest
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

  Cancelling due to test failure: 3 tests still running
        PASS [   2.815s] slatedb transaction_manager::tests::prop_inv_disjoint_active_and_committed_sets
        PASS [   1.345s] slatedb transaction_manager::tests::prop_inv_min_active_seq_correctness
        PASS [   1.380s] slatedb transaction_manager::tests::prop_inv_ssi_read_write_conflict_detection
────────────
     Summary [  49.673s] 1059/1332 tests run: 1058 passed, 1 failed, 1 skipped
        FAIL [  30.056s] slatedb db_reader::tests::db_reader_get_returns_correct_merge_result_after_reestablish_from_l0
warning: 273/1332 tests were not run due to test failure (run with --no-fail-fast to run all tests, or run with --max-fail)
```

Raw Logs: 

[flaky-test-raw-logs.txt](https://github.com/user-attachments/files/26251354/flaky-test-raw-logs.txt)

### PR DESCRIPTION
**Pull request by agavra**
fixes #1439

### CODE REVIEW

File: slatedb/src/db_reader.rs [hunk 1]
```diff
@@ -2385,17 +2329,18 @@ mod tests {
             tokio::task::yield_now().await;
         }
 
-        // Drive the reader poller with the shared mock clock so it reestablishes
-        // from the new manifest that now includes the L0.
-        clock.advance(Duration::from_millis(100)).await;
-
+        let timeout = Duration::from_secs(5);
```
Comment (agavra) [inline slatedb/src/db_reader.rs]: decreased from 30 -> 5s because it should be pretty quick and this way it times out sooner if there's a bug

Comment (criccomini) [reply slatedb/src/db_reader.rs]: I strongly prefer 30 or even 60s on this. The Github action runners are a dumpster fire and I've seen them hang for a very long time. I'd like to avoid timing out because the action runner hangs for 10-20 seconds. 😬

Comment (agavra) [reply slatedb/src/db_reader.rs]: Fair enough! I guess if the GH runner runs for 10 min then fails on a timeout that's more annoying than hanging for a bit more
