### PR TITLE
Throttle WAL writes even if await_durable is false

### LINKED ISSUE #294: Bencher runs out of memory
**Describe the bug**
Bencher will use 30GiB+ of memory when running the 80% or 100% put percentage with concurrency=4. This happens only when the WAL is enabled.

**To Reproduce**
Run the bencher with `wal_enabled = true` and wait for the 80_4 or 100_4 commands to run.

**Expected behavior**
I expect the memory to hover around 1GiB. This is what it looks like with WAL disabled.

**Screenshots**
Screenshot 2024-11-01 at 9 21 49 AM

** Build **
Running on main as of this GH issue. This issue happened before #290, too.

**Additional context**
I noticed the WAL files look like this with write concurrency set to 4:

```
% ls -lh slatedb-lfs/slatedb-bencher_80_4/wal
total 3945712
-rw-r--r--  1 chrisriccomini  wheel    80B Nov  1 09:21 00000000000000000001.sst
-rw-r--r--  1 chrisriccomini  wheel   236M Nov  1 09:21 00000000000000000002.sst
-rw-r--r--  1 chrisriccomini  wheel   512M Nov  1 09:21 00000000000000000003.sst
-rw-r--r--  1 chrisriccomini  wheel   1.2G Nov  1 09:21 00000000000000000004.sst
```

With write concurrency set to 1, it looks more normal:

```
% ls -lh slatedb-lfs/slatedb-bencher_80_1/wal
total 17501224
-rw-r--r--  1 chrisriccomini  wheel    80B Nov  1 09:20 00000000000000000001.sst
-rw-r--r--  1 chrisriccomini  wheel   106M Nov  1 09:20 00000000000000000002.sst
-rw-r--r--  1 chrisriccomini  wheel   123M Nov  1 09:20 00000000000000000003.sst
-rw-r--r--  1 chrisriccomini  wheel   136M Nov  1 09:20 00000000000000000004.sst
-rw-r--r--  1 chrisriccomini  wheel   164M Nov  1 09:20 00000000000000000005.sst
-rw-r--r--  1 chrisriccomini  wheel   139M Nov  1 09:20 00000000000000000006.sst
-rw-r--r--  1 chrisriccomini  wheel   126M Nov  1 09:20 00000000000000000007.sst
-rw-r--r--  1 chrisriccomini  wheel   123M Nov  1 09:20 00000000000000000008.sst
-rw-r--r--  1 chrisriccomini  wheel    79M Nov  1 09:20 00000000000000000009.sst
-rw-r--r--  1 chrisriccomini  wheel    50M Nov  1 09:20 00000000000000000010.sst
-rw-r--r--  1 chrisriccomini  wheel    34M Nov  1 09:20 00000000000000000011.sst
-rw-r--r--  1 chrisriccomini  wheel    25M Nov  1 09:20 00000000000000000012.sst
-rw-r--r--  1 chrisriccomini  wheel    19M Nov  1 09:20 00000000000000000013.sst
-rw-r--r--  1 chrisriccomini  wheel    85M Nov  1 09:20 00000000000000000014.sst
-rw-r--r--  1 chrisriccomini  wheel    73M Nov  1 09:20 00000000000000000015.sst
-rw-r--r--  1 chrisriccomini  wheel    35M Nov  1 09:20 00000000000000000016.sst
-rw-r--r--  1 chrisriccomini  wheel   8.2M Nov  1 09:20 00000000000000000017.sst
-rw-r--r--  1 chrisriccomini  wheel    96M Nov  1 09:20 00000000000000000018.sst
-rw-r--r--  1 chrisriccomini  wheel    64M Nov  1 09:20 00000000000000000019.sst
-rw-r--r--  1 chrisriccomini  wheel    54M Nov  1 09:20 00000000000000000020.sst
```

### PR DESCRIPTION
**Pull request by criccomini**
This commit adds backpressure even in cases where the writer is not waiting for durable writes. Before, we were applying backpressure by capping the number of L0 memtables in object storage and capping the number of unflushed memtables. This would mostly work, but if writers went too fast, they could fill very large WAL SST files before 4 memtables were flushed. We experienced this most acutely when disabling durable writes all together, as it meant writers would not even wait for writes to be written to WAL object storage.

Now, we simply cap how much total memory we're allowed to use for unflushed data, whether that data is in `imm_wal` or `imm_mem_table`. If we exceed this amount of memory, we apply backpressure until one of the unflushed tables gets flushed (whether it's in the WAL or memtable queue).

I wrote a kind of silly test to verify that the WALs at least stack up when they exceed `l0_sst_size_bytes`. It doesn't actually verify backpressure is applied, but it at least mimics the memtable backpressure test we had.

Closes #294

### CODE REVIEW

File: src/db_common.rs [hunk 1]
```diff
@@ -19,4 +19,16 @@ impl DbInner {
             .send(FlushThreadMsg::Flush(None))?;
         Ok(())
     }
+
+    pub(crate) fn maybe_freeze_wal(
+        &self,
+        guard: &mut RwLockWriteGuard<'_, DbState>,
+    ) -> Result<(), SlateDBError> {
+        if guard.wal().size() < 64 * 1024 * 1024 {
```
Comment (agavra) [inline src/db_common.rs:27]: let's make sure to use the same value in the db options for L0 max size in bytes

File: src/db.rs [hunk 2]
```diff
@@ -226,7 +229,31 @@ impl DbInner {
...
     }
 
-    pub(crate) async fn maybe_apply_backpressure(&self) {
+    #[inline]
+    pub(crate) async fn maybe_apply_wal_backpressure(&self) {
+        loop {
+            let table = {
+                let guard = self.state.read();
+                let state = guard.state();
+                if state.imm_wal.len() <= 4 {
```
Comment (agavra) [inline src/db.rs:238]: ditto: we can probably just use the same config from `self.options.max_unflushed_memtable` instead of creating a new one

**Review by agavra — APPROVED** [review]
This LGTM! Thanks for all the discussions on this, I ended up learning a lot about Slate

File: src/config.rs [hunk 3]
```diff
@@ -356,6 +356,10 @@ pub struct DbOptions {
     /// you may benefit from setting this higher (if you have enough memory available)
     pub filter_bits_per_key: u32,
 
+    /// The max number of unflushed WAL SSTables. Writes will be paused if there are
+    /// more unflushed WAL SSTables than this value.
+    pub max_unflushed_wal: usize,
```
Comment (calavera) [inline src/config.rs:361]: can you add this new field to the examples of configuration files in this file's header?

Comment (criccomini) [reply src/config.rs:367]: Done! 3db24e8

File: src/db.rs [hunk 4]
```diff
@@ -236,8 +236,13 @@ impl DbInner {
         let (tx, rx) = tokio::sync::oneshot::channel();
         let batch_msg = WriteBatchMsg::WriteBatch(WriteBatchRequest { batch, done: tx });
 
-        self.maybe_apply_backpressure().await;
-        self.write_notifier.send(batch_msg).ok();
+        if self.wal_enabled() {
+            self.maybe_apply_wal_backpressure().await;
+        }
+        self.maybe_apply_memtable_backpressure().await;
```
Comment (rodesai) [inline src/db.rs:242]: instead of gating writes on either the imm wal list or the imm memtable list being full, we could:

1. move this line behind an `else` - that way we apply backpressure at the level that the writer is writing into (wal vs memtable).
2. pause wal flushes when the flush thread sees that there are too many immutable memtables

The benefit is that while l0/memtable is full, we can still write data into the wal until that queue fills up.

**Review by vigneshc — APPROVED** [review]
LGTM!

File: src/db.rs [hunk 5]
```diff
@@ -254,48 +251,58 @@ impl DbInner {
     }
 
     #[inline]
-    pub(crate) async fn maybe_apply_wal_backpressure(&self) {
+    pub(crate) async fn maybe_apply_backpressure(&self) {
         loop {
-            let table = {
+            let mem_size_bytes = {
```
Comment (agavra) [inline src/db.rs:256]: nice! I like this approach to limit memory better than the original approach

**Comment by criccomini** [comment]
I'm attaching [results-303.zip](https://github.com/user-attachments/files/17639108/results-303.zip), which contains a bencher run with object store cache disabled and WAL enabled:

```
diff --git a/src/bencher/SlateDb.toml b/src/bencher/SlateDb.toml
index 0db7598..c61dc9a 100644
--- a/src/bencher/SlateDb.toml
+++ b/src/bencher/SlateDb.toml
@@ -1,5 +1,5 @@
-wal_enabled = false
+wal_enabled = true
 flush_interval = "100ms"
 
-[object_store_cache_options]
-root_folder = "/tmp/slatedb-cache"
+# [object_store_cache_options]
+# root_folder = "/tmp/slatedb-cache"
```

The results seem reasonable to me. Here are 4 writers with 100% puts:



Holds steady at about 20k writes/sec with 8192 byte value payloads. Roughly 165MB/s. I also verified the memory stays under 2 gigs the whole time.

File: src/db_common.rs [hunk 6]
```diff
@@ -18,4 +20,21 @@ impl DbInner {
...
     }
+
+    pub(crate) fn maybe_freeze_wal(
+        &self,
+        guard: &mut RwLockWriteGuard<'_, DbState>,
+    ) -> Result<(), SlateDBError> {
+        // Use L0 SST size as the threshold for freezing a WAL table because
+        // a single WAL table gets added to a single L0 SST. If the WAL table
+        // were allowed to grow larger than the L0 SST threshold, the L0 SST
+        // size would threshold.
```
[the remark this answers is not in the document]
Comment (criccomini) [reply src/db_common.rs]: ee70260
